#!/bin/sh
#
# Author:           Marin Atanasov Nikolov <dnaeon@gmail.com>
#
### BEGIN INIT INFO
# Provides:          vpoller-worker
# Required-Start:    
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6 
# Short-Description: VPoller Worker daemon
### END INIT INFO
 
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
DESC="vpoller-worker daemon"
NAME=vpoller-worker
DAEMON=/usr/bin/vpoller-worker
SCRIPTNAME=/etc/init.d/"$NAME"
MGMT_INTERFACE="tcp://localhost:10000"

set -e
 
# /etc/init.d/vpoller-worker: start and stop the VPoller Worker daemon

. /lib/lsb/init-functions
 
do_start() {
    ${DAEMON} -d start
}

do_stop() {
    ${DAEMON} -e ${MGMT_INTERFACE} stop
}
 
do_status() {
    ${DAEMON} -e ${MGMT_INTERFACE} status
}
 
case "${1}" in
    start)
        do_start
        ;;
    reset|stop)
        do_stop
        ;;
    status)
        do_status
        ;;
    reload|restart|force-reload)
        do_stop
        do_start
        ;;
    *)
        log_success_msg "usage: ${0} {start|stop|status|reload|restart|force-reload|reset}" >&2
        ;;
esac
