#!/usr/bin/env sh
# Simple wrapper script to use with Zabbix and the C client of vPoller

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
whitespace="[[:space:]]"
_vsphere=
_args=''

### Process command line with spaces in
for i in "$@"
do
    if [[ $i =~ $whitespace ]]
    then
       _args="${_args} \"$i\""
    else
       _args="${_args} $i"
    fi
done

### Processing opts to retrieve vSphere host
while getopts "hvDm:n:p:r:t:e:V:k:U:P:o:H:" opt
do
    case "${opt}" in
    V)  _vsphere=$OPTARG ;;
    esac
done
shift $((OPTIND-1))

### Filter the property name out of the args
_property_name=`echo ${_args} | sed -ne 's|.* -p \([a-zA-Z\.]*\)|\1|p'`

### Detect if vcenter SDK is available
_url="https://${_vsphere}/sdk"
_curl_bin=`which curl`
_curl_options="--connect-timeout 3 -k"

if [ ! -f $_curl_bin ]
then
  echo "ZBX_NOTSUPPORTED no curl"
  exit 1
fi

${_curl_bin} ${_curl_options} ${_url} > /dev/null 2>&1

if [ $? -ne 0 ]
then
  echo "ZBX_NOTSUPPORTED no SDK"
  exit 1
fi

### Detect if vpoller proxy is working:
### Disable this check if the proxy is not running on this host or change the url"
if [ -f /usr/bin/vpoller-proxy ]
then
  _running=`/usr/bin/vpoller-proxy -e tcp://localhost:9999 status | grep -w running | wc -l`

  if [ $_running -eq 0 ]
  then
    echo "ZBX_NOTSUPPORTED no vpoller proxy"
    exit 1
  fi
fi

# Rename property as it might contain dots in the complete property name, so that 'jq' can parse it
sh -c "vpoller-cclient ${_args} 2>/dev/null" | jq -r ".result[0] | {\"property\": .[\"${_property_name}\"]}.property"
