#!/usr/bin/env python
#
# Copyright (c) 2013 Marin Atanasov Nikolov <dnaeon@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer
#    in this position and unchanged.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
vmpoller-client is an application used for polling objects' information from a VMware vCenter server.

It is intended to be integrated into a Zabbix template for polling of ESX hosts and Datastores properties.
"""

import sys
import logging

from vmpoller.core import VMPollerClient
from docopt import docopt

def main():

    usage="""
Usage:
  vmpoller-client [-r <retries>] [-t <timeout>] [-o <logfile>] (-D|-H) -c discover -V <vcenter> -e <endpoint>
  vmpoller-client [-r <retries>] [-t <timeout>] [-o <logfile>] -H -n <name> -p <property> -c poll -V <vcenter> -e <endpoint>
  vmpoller-client [-r <retries>] [-t <timeout>] [-o <logfile>] -D -u <datastore-url> -p <property> -c poll -V <vcenter> -e <endpoint>
  vmpoller-client --help
  vmpoller-client --version

Options:
  -h, --help                                Display this usage info
  -v, --version                             Display version and exit
  -D, --datastores                          Retrieve a datastore object property
  -H, --hosts                               Retrieve a host object property
  -V <vcenter>, --vcenter <vcenter>         The vCenter server to send the request to
  -c <cmd>, --command <cmd>                 The command to perform, either "poll" or "discover"
  -n <name>, --name <name>                  Name of the ESX host, only applicable to hosts object type
  -p <property>, --property <property>      Name of the property as defined by the vSphere Web SDK
  -u <datastore-url>, --url <datastore-url> Datastore URL, only applicable to datastores object type
  -r <retries>, --retries <retries>         Number of time to retry if a request times out [default: 3]
  -t <timeout>, --timeout <timeout>         Timeout after that period of milliseconds [default: 3000]
  -e <endpoint>, --endpoint <endpoint>      Endpoint of ZeroMQ Proxy/Broker the client connects to
                                            [default: tcp://localhost:10123]
  -o <logfile>, --output <logfile>          Specify the log file to use when performing the poll
                                            [default: /var/log/vmpoller/vmpoller-client.log]

"""

    args = docopt(usage, version="1.0.0")

    if args["--output"] == "-":
        logging.basicConfig(stream=sys.stdout,
                            format='%(asctime)s - %(levelname)s - vmpoller-client[%(process)s]: %(message)s',
                            level=logging.DEBUG)
    else:
        logging.basicConfig(filename=args["--output"],
                            format='%(asctime)s - %(levelname)s - vmpoller-client[%(process)s]: %(message)s',
                            level=logging.DEBUG)
        
    client = VMPollerClient(endpoint=args["--endpoint"], retries=int(args["--retries"]), timeout=int(args["--timeout"]))

    msg = { "type":    "hosts" if args["--hosts"] else "datastores",
            "vcenter":  args["--vcenter"],
            "name":     args["--name"],
            "info.url": args["--url"],
            "cmd":      args["--command"],
            "property": args["--property"],
            }
    
    result = client.run(msg)
    print result
    
if __name__ == '__main__':
    main()

