#!/bin/sh
#
# Author:           Marin Atanasov Nikolov <dnaeon@gmail.com>
#
### BEGIN INIT INFO
# Provides:          vpoller-worker
# Required-Start:
# Required-Stop:
# X-Start-Before:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: VPoller Worker daemon
### END INIT INFO
# /etc/init.d/vpoller-worker: start and stop the VPoller Worker daemon
set -e

### Change depending on installation: standalone or together with zabbix
USER=zabbix
GROUP=zabbix

### Variables
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
DESC="vpoller-worker daemon"
NAME=vpoller-worker
DAEMON=`which vpoller-worker`
SCRIPTNAME=/etc/init.d/"$NAME"
MGMT_INTERFACE="tcp://localhost:10000"
PID_DIR=/var/run/vpoller
LOG_DIR=/var/log/vpoller
PID=${PID_DIR}/vpoller-proxy.pid

### Create needed directories and set right permissions
if [ ! -d ${PID_DIR} ]; then
  mkdir -p ${PID_DIR}
  chown ${USER}:${GROUP} ${PID_DIR}
fi
if [ ! -d ${LOG_DIR} ]; then
  mkdir -p ${LOG_DIR}
  chown ${USER}:${GROUP} ${LOG_DIR}
fi

. /lib/lsb/init-functions

do_start() {
  log_daemon_msg "Starting $DESC" "$NAME"
  start-stop-daemon -c ${USER}:${GROUP} --oknodo --start --pidfile $PID \
    --exec $DAEMON -- -d start >/dev/null 2>&1
  case "$?" in
    0) log_end_msg 0 ;;
    *) log_end_msg 1; exit 1 ;;
    esac

#    ${DAEMON} -d start
}

do_stop() {
  log_daemon_msg "Stopping $DESC" "$NAME"
  start-stop-daemon --oknodo --stop --pidfile $PID
  case "$?" in
    0) log_end_msg 0 ;;
    *) log_end_msg 1; exit 1 ;;
  esac
    #${DAEMON} -e ${MGMT_INTERFACE} stop
}

do_status() {
    ${DAEMON} -e ${MGMT_INTERFACE} status
}

case "${1}" in
    start)
        do_start
        ;;
    reset|stop)
        do_stop
        ;;
    status)
        do_status
        ;;
    reload|restart|force-reload)
        do_stop
        do_start
        ;;
    *)
        log_success_msg "usage: ${0} {start|stop|status|reload|restart|force-reload|reset}" >&2
        ;;
esac
